name: ci

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 🏗️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup pnpm 🏗️
        uses: pnpm/action-setup@v2

      - name: setup node.js 🏗️
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: install dependencies 📦
        run: pnpm install --frozen-lockfile

      - name: build 👷
        run: pnpm run build

      - name: test 🧑‍🔬
        run: pnpm run test

      - name: lint 💅
        run: pnpm run lint

      - name: exports 🚚
        run: pnpm run exports

      - name: tsc 🚨
        run: pnpm run tsc
