name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: pnpm/action-setup@v2.1.0
      with:
        version: latest

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        cache: "pnpm"
        registry-url: https://registry.npmjs.org        
        node-version-file: '.nvmrc'

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build --if-present

    - name: Test
      run: pnpm run test

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
