name: Publish to npm

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        cache: "pnpm"

    - uses: pnpm/action-setup@v2.1.0
      with:
        version: latest

    - name: Install dependencies
      run: pnpm ci

    - name: Build
      run: pnpm run build --if-present

    - name: Test
      run: pnpm run test
    
    - name: Publish to NPM
      if: ${{ success() }}
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
