name: release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 🏗️ checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: 🏗️ setup pnpm
        uses: pnpm/action-setup@v3

      - name: 🏗️ setup node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: 📦 install dependencies
        run: pnpm install --frozen-lockfile

      - name: 👷 build
        run: pnpm run build

      - name: 📦 configure npm for authentication
        run: |
          npm config set //registry.npmjs.org/:_authToken "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 🚀 create release pull request or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
